import { Challenge, Stat, LeaderboardEntry } from '@/types'

export const STATS: Stat[] = [
  { label: 'Active Challenges', value: '124', change: '+12%', iconType: 'zap' },
  { label: 'MON Rewards Paid', value: '50k+', change: '+8%', iconType: 'wallet' },
  { label: 'Total Participants', value: '12.5k', change: '+25%', iconType: 'users' },
]

export const CHALLENGES: Challenge[] = [
  {
    id: '1',
    name: '30-Day Yoga Streak',
    description: 'Complete 20 mins of daily yoga. Verify via photo proof or wearable data integration.',
    category: 'Yoga',
    prizePool: '470 MON',
    entryFee: '10 MON',
    reward: '~12.5 MON',
    progress: 65,
    participants: 47,
    daysLeft: 10,
    peopleQuit: 8,
    profitIfComplete: '~12.5 MON',
    iconType: 'activity',
    gradient: 'from-purple-500/20 to-fuchsia-500/20',
  },
  {
    id: '2',
    name: '10K Steps Challenge',
    description: 'Hit 10,000 steps every day for a week. Syncs with Apple Health & Google Fit.',
    category: 'Cardio',
    prizePool: '3,200 MON',
    entryFee: '25 MON',
    reward: '~32 MON',
    progress: 88,
    participants: 128,
    daysLeft: 5,
    peopleQuit: 12,
    profitIfComplete: '~32 MON',
    iconType: 'zap',
    gradient: 'from-blue-500/20 to-emerald-500/20',
  },
  {
    id: '3',
    name: '7-Day Run Streak',
    description: 'Run at least 2 km every day for 7 days. Log your run with a screenshot or wearable.',
    category: 'Cardio',
    prizePool: '120 MON',
    entryFee: '1 MON',
    reward: '~1.5 MON',
    progress: 55,
    participants: 120,
    daysLeft: 3,
    peopleQuit: 18,
    profitIfComplete: '~1.5 MON',
    iconType: 'zap',
    gradient: 'from-emerald-500/20 to-teal-500/20',
  },
  {
    id: '4',
    name: 'Plant-Based Week',
    description: 'Eat plant-based meals for 7 days. Upload meal photos to verify and earn rewards.',
    category: 'Nutrition',
    prizePool: '120 MON',
    entryFee: '5 MON',
    reward: '~7 MON',
    progress: 45,
    participants: 24,
    daysLeft: 4,
    peopleQuit: 3,
    profitIfComplete: '~7 MON',
    iconType: 'activity',
    gradient: 'from-emerald-500/20 to-hc-amber/20',
  },
  {
    id: '5',
    name: '5AM Meditation Club',
    description: 'Wake up and check in before 5:30 AM. Build discipline and earn rewards.',
    category: 'Mindfulness',
    prizePool: '3,000 MON',
    entryFee: '15 MON',
    reward: '~20 MON',
    progress: 92,
    participants: 200,
    daysLeft: 14,
    peopleQuit: 22,
    profitIfComplete: '~20 MON',
    iconType: 'trophy',
    gradient: 'from-hc-amber/20 to-orange-500/20',
  },
  {
    id: '6',
    name: '1 MON Daily Push-Up',
    description: 'Do 20 push-ups every day for 14 days. Photo or video proof. Low stake, high habit.',
    category: 'Strength',
    prizePool: '84 MON',
    entryFee: '1 MON',
    reward: '~1.2 MON',
    progress: 30,
    participants: 84,
    daysLeft: 10,
    peopleQuit: 11,
    profitIfComplete: '~1.2 MON',
    iconType: 'flame',
    gradient: 'from-orange-500/20 to-red-500/20',
  },
  {
    id: '7',
    name: 'HIIT 5-Day Burn',
    description: 'Complete a 15-min HIIT session daily for 5 days. Record with fitness app or video.',
    category: 'HIIT',
    prizePool: '95 MON',
    entryFee: '1 MON',
    reward: '~1.4 MON',
    progress: 60,
    participants: 95,
    daysLeft: 2,
    peopleQuit: 9,
    profitIfComplete: '~1.4 MON',
    iconType: 'zap',
    gradient: 'from-red-500/20 to-fuchsia-500/20',
  },
  {
    id: '8',
    name: '30-Day Plank Challenge',
    description: 'Hold a plank every day—increase duration each week. Photo proof accepted.',
    category: 'Strength',
    prizePool: '450 MON',
    entryFee: '15 MON',
    reward: '~18 MON',
    progress: 40,
    participants: 30,
    daysLeft: 18,
    peopleQuit: 5,
    profitIfComplete: '~18 MON',
    iconType: 'target',
    gradient: 'from-slate-500/20 to-zinc-500/20',
  },
  {
    id: '9',
    name: 'Hydration Week',
    description: 'Log 8 glasses of water daily for 7 days. Simple check-in each day.',
    category: 'Lifestyle',
    prizePool: '60 MON',
    entryFee: '1 MON',
    reward: '~1.3 MON',
    progress: 70,
    participants: 60,
    daysLeft: 2,
    peopleQuit: 7,
    profitIfComplete: '~1.3 MON',
    iconType: 'activity',
    gradient: 'from-cyan-500/20 to-blue-500/20',
  },
]

export const LEADERBOARD: LeaderboardEntry[] = [
  { name: '0x3f...82A1', progress: 100, days: '30/30' },
  { name: '0x9a...B2C9', progress: 95, days: '29/30' },
  { name: '0x21...D5F1', progress: 90, days: '27/30' },
  { name: 'You', progress: 85, days: '26/30', isUser: true },
  { name: '0x55...E8R9', progress: 80, days: '25/30' },
  { name: '0x7a...C3D1', progress: 75, days: '23/30' },
  { name: '0x1b...F4E2', progress: 70, days: '21/30' },
  { name: '0x4c...A9B8', progress: 65, days: '20/30' },
]

/** Dummy leaderboard entries when a challenge has no on-chain participants yet. */
export const DUMMY_CHALLENGE_LEADERBOARD: LeaderboardEntry[] = [
  { name: '0x3f...82A1', progress: 100, days: '30/30' },
  { name: '0x9a...B2C9', progress: 97, days: '29/30' },
  { name: '0x21...D5F1', progress: 90, days: '27/30' },
  { name: 'You', progress: 87, days: '26/30', isUser: true },
  { name: '0x55...E8R9', progress: 83, days: '25/30' },
  { name: '0x7a...C3D1', progress: 77, days: '23/30' },
  { name: '0x1b...F4E2', progress: 70, days: '21/30' },
  { name: '0x4c...A9B8', progress: 67, days: '20/30' },
  { name: '0x2e...F1A3', progress: 60, days: '18/30' },
  { name: '0x8d...C5B7', progress: 53, days: '16/30' },
]

/** Dummy usernames for "quit" list in challenge detail (committed then quit). */
export const DUMMY_QUIT_USERS = [
  '0x4a...B1',
  '0x7c...D2',
  '0x1f...E3',
  '0x9b...A4',
  '0x2d...C5',
  '0x6e...F6',
  '0x3a...87',
  '0x5c...29',
]

/** Dummy dashboard: "my" challenges when wallet has none (for demo). */
export const DUMMY_MY_CHALLENGES = [
  { id: '1', name: '30-Day Yoga Streak', progress: 65, daysLeft: 10, checkIns: 20, durationDays: 30, entryFee: '10 MON', profitIfComplete: '~12.5 MON' },
  { id: '2', name: '10K Steps Challenge', progress: 88, daysLeft: 5, checkIns: 7, durationDays: 7, entryFee: '25 MON', profitIfComplete: '~32 MON' },
  { id: '6', name: '1 MON Daily Push-Up', progress: 30, daysLeft: 10, checkIns: 4, durationDays: 14, entryFee: '1 MON', profitIfComplete: '~1.2 MON' },
]
